sudo: required
services:
  - docker

before_install:
  - docker build -t handzel/react-test -f ./client/Dockerfile.dev ./client
  - docker build -t handzel/server-test -f ./server/Dockerfile.dev ./server

script: 
  - docker run -e CI=true handzel/react-test npm test -- --coverage
  - docker run -e CI=true handzel/server-test npm test  

after_success:
  - docker build -t handzel/m-client ./client
  - docker build -t handzel/m-nginx ./nginx
  - docker build -t handzel/m-server ./server
  - docker build -t handzel/m-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take above images and push to docker hub
  - docker push handzel/m-client
  - docker push handzel/m-nginx
  - docker push handzel/m-server
  - docker push handzel/m-worker
